"""empty message

Revision ID: 62d4d27afcf
Revises: 453729c2bc21
Create Date: 2014-11-03 14:52:53.884479

"""

# revision identifiers, used by Alembic.
revision = '62d4d27afcf'
down_revision = '453729c2bc21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dlannotations', sa.Column('selected_texts_json', sa.Text(convert_unicode=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dlannotations', 'selected_texts_json')
    ### end Alembic commands ###
